//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBuyPlay.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WcfBuyPay")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigo_usuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faccesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecNacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                if ((object.ReferenceEquals(this.claveField, value) != true)) {
                    this.claveField = value;
                    this.RaisePropertyChanged("clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo_usu {
            get {
                return this.codigo_usuField;
            }
            set {
                if ((this.codigo_usuField.Equals(value) != true)) {
                    this.codigo_usuField = value;
                    this.RaisePropertyChanged("codigo_usu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string facceso {
            get {
                return this.faccesoField;
            }
            set {
                if ((object.ReferenceEquals(this.faccesoField, value) != true)) {
                    this.faccesoField = value;
                    this.RaisePropertyChanged("facceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecNac {
            get {
                return this.fecNacField;
            }
            set {
                if ((object.ReferenceEquals(this.fecNacField, value) != true)) {
                    this.fecNacField = value;
                    this.RaisePropertyChanged("fecNac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Agregar", ReplyAction="http://tempuri.org/IService1/AgregarResponse")]
        string Agregar(ProyectoBuyPlay.ServiceReference1.Usuario u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Agregar", ReplyAction="http://tempuri.org/IService1/AgregarResponse")]
        System.Threading.Tasks.Task<string> AgregarAsync(ProyectoBuyPlay.ServiceReference1.Usuario u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        string Login(ProyectoBuyPlay.ServiceReference1.Usuario u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(ProyectoBuyPlay.ServiceReference1.Usuario u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscarUsuario", ReplyAction="http://tempuri.org/IService1/buscarUsuarioResponse")]
        ProyectoBuyPlay.ServiceReference1.Usuario buscarUsuario(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/buscarUsuario", ReplyAction="http://tempuri.org/IService1/buscarUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoBuyPlay.ServiceReference1.Usuario> buscarUsuarioAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Contra", ReplyAction="http://tempuri.org/IService1/ContraResponse")]
        string Contra(ProyectoBuyPlay.ServiceReference1.Usuario u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Contra", ReplyAction="http://tempuri.org/IService1/ContraResponse")]
        System.Threading.Tasks.Task<string> ContraAsync(ProyectoBuyPlay.ServiceReference1.Usuario u);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ProyectoBuyPlay.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ProyectoBuyPlay.ServiceReference1.IService1>, ProyectoBuyPlay.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Agregar(ProyectoBuyPlay.ServiceReference1.Usuario u) {
            return base.Channel.Agregar(u);
        }
        
        public System.Threading.Tasks.Task<string> AgregarAsync(ProyectoBuyPlay.ServiceReference1.Usuario u) {
            return base.Channel.AgregarAsync(u);
        }
        
        public string Login(ProyectoBuyPlay.ServiceReference1.Usuario u) {
            return base.Channel.Login(u);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(ProyectoBuyPlay.ServiceReference1.Usuario u) {
            return base.Channel.LoginAsync(u);
        }
        
        public ProyectoBuyPlay.ServiceReference1.Usuario buscarUsuario(string usuario) {
            return base.Channel.buscarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<ProyectoBuyPlay.ServiceReference1.Usuario> buscarUsuarioAsync(string usuario) {
            return base.Channel.buscarUsuarioAsync(usuario);
        }
        
        public string Contra(ProyectoBuyPlay.ServiceReference1.Usuario u) {
            return base.Channel.Contra(u);
        }
        
        public System.Threading.Tasks.Task<string> ContraAsync(ProyectoBuyPlay.ServiceReference1.Usuario u) {
            return base.Channel.ContraAsync(u);
        }
    }
}
